# Helper role for users who manage BeaconPolicy access.
#
# Grants full permissions on BeaconPolicy resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: beacon
    app.kubernetes.io/managed-by: kustomize
  name: beaconpolicy-admin-role
rules:
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - beaconpolicies
  verbs:
  - '*'
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - beaconpolicies/status
  verbs:
  - get
