# Helper role for users who edit BeaconPolicy resources.
#
# Does not grant RBAC management permissions.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: beacon
    app.kubernetes.io/managed-by: kustomize
  name: beaconpolicy-editor-role
rules:
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - beaconpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - beaconpolicies/status
  verbs:
  - get
