# Helper role for users who edit StarvationEvent resources.
#
# Does not grant RBAC management permissions.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: Beacon
    app.kubernetes.io/managed-by: kustomize
  name: starvationevent-editor-role
rules:
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - starvationevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.beacon.dev
  resources:
  - starvationevents/status
  verbs:
  - get
