## Beacon sample resources ##
resources:
- sample-api-deployment.yaml
- autoscaling_v1alpha1_beaconpolicy.yaml
- autoscaling_v1alpha1_starvationevent.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
