apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - name: api
        image: nginx:stable
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
