# Use this through config/default.
# It depends on names and namespaces from the full overlay.
resources:
- bases/autoscaling.beacon.dev_beaconpolicies.yaml
- bases/autoscaling.beacon.dev_starvationevents.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] Enable these patches for CRD conversion webhooks.
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] Enable this config for CRD webhook references.
#configurations:
#- kustomizeconfig.yaml
